repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
  
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6   # match your clang-format version
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|h)$

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: bash -c 'clang-tidy $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(cpp|cc)$") -- -Iinclude || true'
        language: system
        pass_filenames: false