pinout:
  MOTOR_LEFT_PIN_1: 5
  MOTOR_LEFT_PIN_2: 6
  MOTOR_RIGHT_PIN_1: 13
  MOTOR_RIGHT_PIN_2: 19
  ENABLE_MOTOR_SHIELD_PIN: 8
  IMU_SDA_PIN: 2
  IMU_SCL_PIN: 3

camera:
  width: 640
  height: 480
  framerate: 30
  hflip: true
  vflip: true
  stream_port: 5123