pinout:
  MOTOR_LEFT_PIN_1: 5
  MOTOR_LEFT_PIN_2: 6
  MOTOR_RIGHT_PIN_1: 13
  MOTOR_RIGHT_PIN_2: 19
  ENABLE_MOTOR_SHIELD_PIN: 8

camera:
  width: 640
  height: 480
  framerate: 5
  hflip: true
  vflip: true

platform_client:
  server_ip: 192.168.15.25
  server_port: 8000